server:
  port: 8081

spring:
  application:
    name: time-tracker-service
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/time_tracking
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      pool-name: SpringBootHikariCP
      connection-timeout: 30000
      max-lifetime: 1800000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

app:
  jwt:
    secret: dmitry
    issuer: dmitry
